#ifndef __EVENTS_H__
#define __EVENTS_H__

typedef enum {
  EVENT_NOOP,
  EVENT_READ_MUSIC_FILE,
  
  // Button events
  EVENT_BUTTON_UP_PRESSED,
  EVENT_BUTTON_UP_RELEASED,
  EVENT_BUTTON_DOWN_PRESSED,
  EVENT_BUTTON_DOWN_RELEASED,
  EVENT_BUTTON_LEFT_PRESSED,
  EVENT_BUTTON_LEFT_RELEASED,
  EVENT_BUTTON_RIGHT_PRESSED,
  EVENT_BUTTON_RIGHT_RELEASED,
  EVENT_BUTTON_A_PRESSED,
  EVENT_BUTTON_A_RELEASED,
  EVENT_BUTTON_B_PRESSED,
  EVENT_BUTTON_B_RELEASED,
} event_t;

void q_init();
void q_emit(event_t *event);
void q_next_event(event_t *event);

#endif